### ISSUE TITLE
FATA 00002 - can't interract with spinnaker

### ISSUE THREAD

**Issue by angegar** [robzienert/tiller#43]
Hi all, 
When i run the following command  
`roer pipeline-template convert jenkins jenkins-from-docker`

i receive 
```
FATA[0002] getting pipeline config: failed unmarshaling pipeline config response: invalid character '<' 
looking for beginning of value
```

Do you have any idea about what could happen ?

Thank you for your help.

**Comment by brandonnelson3** [comment]
@angegar Hi,

I'm not 100% certain here, but roer is written in Golang, and that is the same error you would get if you happened to be pointed to a path that returned html instead of json. 

What host:port are you using? 

I think it should be localhost:8084 assuming you are running on the same machine.

**Comment by angegar** [comment]
Finally that was an authentication issues i have to retrieve a global pass token and use the option --as in my roer command to make it works.

Thank you for your help
